# Use root/example as user/password credentials
networks:
  demo-docker:
    driver: bridge

services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    expose:
      - '3306'
    networks:
      - demo-docker
  backend:
    build: 
      context: ./be_docker
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./be_docker/src:/app/src
    command: npm run start:prod
    environment:
      - HOST=host.docker.internal
      - PORT=3307
    env_file:
      - ./be_docker/.env
    networks:
      - demo-docker
  frontend:
    image: nginx
    # build: 
    #   context: ./fe_docker
    #   dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./fe_docker/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - demo-docker
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - demo-docker
volumes:
  jenkins_home:
