# Use root/example as user/password credentials
services:
  backend:
    build: 
      context: ./be_docker
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./be_docker/src:/app/src
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3307:3306'
    expose:
      - '3306'
  
